-- Glocal Summit — Supabase schema.
-- Run this in the Supabase SQL editor FIRST, then run seed.sql.

-- ---------- Tables ----------
create table if not exists groups (
  id          bigint generated by default as identity primary key,
  name        text not null,
  color       text not null default '#cc2027',
  sort_order  int  not null default 0
);

create table if not exists labs (
  id          bigint generated by default as identity primary key,
  group_id    bigint not null references groups(id) on delete cascade,
  name        text not null,
  sort_order  int  not null default 0
);

create table if not exists participants (
  id            bigint generated by default as identity primary key,
  stt           text,
  title         text,
  name          text not null,
  country       text,
  org           text,
  org_logo_url  text,
  role          text,
  email         text not null unique,
  coordinator   text,
  group_id      bigint references groups(id) on delete set null,
  self_registered boolean not null default false
);

create table if not exists selections (
  id              bigint generated by default as identity primary key,
  participant_id  bigint not null references participants(id) on delete cascade,
  lab_id          bigint not null references labs(id) on delete cascade,
  created_at      timestamptz not null default now(),
  unique (participant_id, lab_id)
);

create table if not exists responses (
  id              bigint generated by default as identity primary key,
  participant_id  bigint not null unique references participants(id) on delete cascade,
  answer          text not null,
  updated_at      timestamptz not null default now()
);

create table if not exists settings (
  key    text primary key,
  value  text
);

-- ---------- Default settings ----------
insert into settings (key, value) values
  ('voting_open', 'true'),
  ('hero_title', 'Choose your research units'),
  ('hero_subtitle', 'RTD Glocal Summit 2026'),
  ('instructions', 'Sign in with your invited email, then pick every research unit you want to join. You can pick more than one, and edit until voting closes.'),
  ('live_default_style', 'bubbles'),
  ('collab_question', 'In the future, what do you expect to collaborate with CTD?'),
  ('allow_registration', 'true')
on conflict (key) do nothing;

-- ---------- Realtime ----------
alter publication supabase_realtime add table selections;
alter publication supabase_realtime add table responses;

-- ---------- Row Level Security ----------
-- Event-grade policy: public read on reference data + selections (for the live
-- view), and open write on the voting/CMS surface. The admin screen is gated
-- client-side. Tighten with Supabase Auth if stronger control is ever needed.
alter table groups        enable row level security;
alter table labs          enable row level security;
alter table participants  enable row level security;
alter table selections    enable row level security;
alter table responses     enable row level security;
alter table settings      enable row level security;

create policy "read groups"        on groups       for select using (true);
create policy "read labs"          on labs         for select using (true);
create policy "read participants"  on participants for select using (true);
create policy "read selections"    on selections   for select using (true);
create policy "read responses"     on responses    for select using (true);
create policy "read settings"      on settings     for select using (true);

create policy "write groups"       on groups       for all using (true) with check (true);
create policy "write labs"         on labs         for all using (true) with check (true);
create policy "write participants" on participants for all using (true) with check (true);
create policy "write selections"   on selections   for all using (true) with check (true);
create policy "write responses"    on responses    for all using (true) with check (true);
create policy "write settings"     on settings     for all using (true) with check (true);
