// Generate src/data/seed.ts and supabase/seed.sql from scripts/participants.csv.
// Run: npm run seed
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// 7 group colors (kept in sync with tokens.css --group-1..7).
const GROUP_COLORS = [
  '#cc2027', '#e8710a', '#1f9e6e', '#2f6fd6', '#7b4bd0', '#128a9c', '#c0327a',
];

// --- Minimal RFC4180 CSV parser (handles quotes + embedded newlines) ---
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c === '\r') { /* skip */ }
    else field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const clean = (s) => (s || '').replace(/\s+/g, ' ').trim();

function splitLabs(topic) {
  if (!topic || !topic.trim()) return [];
  return topic.split(/\s*[-;]\s*/).map((s) => s.replace(/\s+/g, ' ').trim()).filter(Boolean);
}

// --- Read & parse ---
const raw = readFileSync(resolve(root, 'scripts/participants.csv'), 'utf8');
const rows = parseCSV(raw).filter((r) => r.some((c) => c && c.trim()));
const header = rows[0];
const col = (name) => header.indexOf(name);
const iSTT = col('STT'), iTitle = col('Danh xưng'), iName = col('Họ tên');
const iCountry = col('Quốc gia'), iOrg = col('Đơn vị Logo'), iRole = col('Chức vụ');
const iEmail = col('Email'), iCoord = col('Coordinator'), iTopic = col('Topic');

const data = rows.slice(1).filter((r) => clean(r[iName]));

// --- Groups (distinct non-empty Topic, verbatim) ---
const groups = [];
const groupByTopic = new Map();
for (const r of data) {
  const topic = clean(r[iTopic]);
  if (!topic || groupByTopic.has(topic)) continue;
  const g = { id: groups.length + 1, name: topic, color: GROUP_COLORS[groups.length % GROUP_COLORS.length], sort_order: groups.length + 1 };
  groups.push(g);
  groupByTopic.set(topic, g);
}

// --- Labs (split per group) ---
const labs = [];
for (const g of groups) {
  splitLabs(g.name).forEach((name, idx) => {
    labs.push({ id: labs.length + 1, group_id: g.id, name, sort_order: idx + 1 });
  });
}

// --- Participants ---
const participants = data.map((r, idx) => {
  const topic = clean(r[iTopic]);
  const g = topic ? groupByTopic.get(topic) : null;
  return {
    id: idx + 1,
    stt: clean(r[iSTT]),
    title: clean(r[iTitle]),
    name: clean(r[iName]),
    country: clean(r[iCountry]),
    org: clean(r[iOrg]),
    org_logo_url: null,
    role: clean(r[iRole]),
    email: clean(r[iEmail]).toLowerCase(),
    coordinator: clean(r[iCoord]),
    group_id: g ? g.id : null,
  };
});

// --- Emit seed.ts ---
const tsOut = `// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
import type { Group, Lab, Participant } from '../types.ts';

export const seedGroups: Group[] = ${JSON.stringify(groups, null, 2)};

export const seedLabs: Lab[] = ${JSON.stringify(labs, null, 2)};

export const seedParticipants: Participant[] = ${JSON.stringify(participants, null, 2)};
`;
mkdirSync(resolve(root, 'src/data'), { recursive: true });
writeFileSync(resolve(root, 'src/data/seed.ts'), tsOut);

// --- Emit seed.sql ---
const sql = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
let sqlOut = `-- AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.\n`;
sqlOut += `-- Run AFTER schema.sql.\n\n`;
sqlOut += `insert into groups (id, name, color, sort_order) values\n`;
sqlOut += groups.map((g) => `  (${g.id}, ${sql(g.name)}, ${sql(g.color)}, ${g.sort_order})`).join(',\n') + '\non conflict (id) do nothing;\n\n';
sqlOut += `insert into labs (id, group_id, name, sort_order) values\n`;
sqlOut += labs.map((l) => `  (${l.id}, ${l.group_id}, ${sql(l.name)}, ${l.sort_order})`).join(',\n') + '\non conflict (id) do nothing;\n\n';
sqlOut += `insert into participants (id, stt, title, name, country, org, org_logo_url, role, email, coordinator, group_id) values\n`;
sqlOut += participants.map((p) => `  (${p.id}, ${sql(p.stt)}, ${sql(p.title)}, ${sql(p.name)}, ${sql(p.country)}, ${sql(p.org)}, ${sql(p.org_logo_url)}, ${sql(p.role)}, ${sql(p.email)}, ${sql(p.coordinator)}, ${p.group_id == null ? 'NULL' : p.group_id})`).join(',\n') + '\non conflict (id) do nothing;\n\n';
sqlOut += `select setval(pg_get_serial_sequence('groups', 'id'), (select max(id) from groups));\n`;
sqlOut += `select setval(pg_get_serial_sequence('labs', 'id'), (select max(id) from labs));\n`;
sqlOut += `select setval(pg_get_serial_sequence('participants', 'id'), (select max(id) from participants));\n`;
mkdirSync(resolve(root, 'supabase'), { recursive: true });
writeFileSync(resolve(root, 'supabase/seed.sql'), sqlOut);

console.log(`Seed generated: ${groups.length} groups, ${labs.length} labs, ${participants.length} participants.`);
console.log('Keynote (no group):', participants.filter((p) => p.group_id == null).map((p) => p.name).join(', ') || 'none');
