// Generate src/data/seed.ts and supabase/seed.sql from scripts/participants.csv.
// Run: npm run seed
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseSheet } from './lib/parse-sheet.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// --- Parse (natural keys) then assign stable ids for the static seed ---
const raw = readFileSync(resolve(root, 'scripts/participants.csv'), 'utf8');
const parsed = parseSheet(raw);

const groups = parsed.groups.map((g, i) => ({ id: i + 1, ...g }));
const groupIdByName = new Map(groups.map((g) => [g.name, g.id]));

const labs = parsed.labs.map((l, i) => ({
  id: i + 1,
  group_id: groupIdByName.get(l.group_name),
  name: l.name,
  sort_order: l.sort_order,
}));

const participants = parsed.participants.map((p, idx) => ({
  id: idx + 1,
  stt: p.stt,
  title: p.title,
  name: p.name,
  country: p.country,
  org: p.org,
  org_logo_url: null,
  role: p.role,
  email: p.email,
  coordinator: p.coordinator,
  group_id: p.topic ? (groupIdByName.get(p.topic) ?? null) : null,
}));

// --- Emit seed.ts ---
const tsOut = `// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
import type { Group, Lab, Participant } from '../types.ts';

export const seedGroups: Group[] = ${JSON.stringify(groups, null, 2)};

export const seedLabs: Lab[] = ${JSON.stringify(labs, null, 2)};

export const seedParticipants: Participant[] = ${JSON.stringify(participants, null, 2)};
`;
mkdirSync(resolve(root, 'src/data'), { recursive: true });
writeFileSync(resolve(root, 'src/data/seed.ts'), tsOut);

// --- Emit seed.sql ---
const sql = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
let sqlOut = `-- AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.\n`;
sqlOut += `-- Run AFTER schema.sql.\n\n`;
sqlOut += `insert into groups (id, name, color, sort_order) values\n`;
sqlOut += groups.map((g) => `  (${g.id}, ${sql(g.name)}, ${sql(g.color)}, ${g.sort_order})`).join(',\n') + '\non conflict (id) do nothing;\n\n';
sqlOut += `insert into labs (id, group_id, name, sort_order) values\n`;
sqlOut += labs.map((l) => `  (${l.id}, ${l.group_id}, ${sql(l.name)}, ${l.sort_order})`).join(',\n') + '\non conflict (id) do nothing;\n\n';
sqlOut += `insert into participants (id, stt, title, name, country, org, org_logo_url, role, email, coordinator, group_id) values\n`;
sqlOut += participants.map((p) => `  (${p.id}, ${sql(p.stt)}, ${sql(p.title)}, ${sql(p.name)}, ${sql(p.country)}, ${sql(p.org)}, ${sql(p.org_logo_url)}, ${sql(p.role)}, ${sql(p.email)}, ${sql(p.coordinator)}, ${p.group_id == null ? 'NULL' : p.group_id})`).join(',\n') + '\non conflict (id) do nothing;\n\n';
sqlOut += `select setval(pg_get_serial_sequence('groups', 'id'), (select max(id) from groups));\n`;
sqlOut += `select setval(pg_get_serial_sequence('labs', 'id'), (select max(id) from labs));\n`;
sqlOut += `select setval(pg_get_serial_sequence('participants', 'id'), (select max(id) from participants));\n`;
mkdirSync(resolve(root, 'supabase'), { recursive: true });
writeFileSync(resolve(root, 'supabase/seed.sql'), sqlOut);

console.log(`Seed generated: ${groups.length} groups, ${labs.length} labs, ${participants.length} participants.`);
console.log('Keynote (no group):', participants.filter((p) => p.group_id == null).map((p) => p.name).join(', ') || 'none');
