// AUTO-GENERATED by scripts/fetch-logos.mjs.
// org string -> local logo path (null = none yet; set via CMS).
const LOGO_MAP: Record<string, string | null> = {
  "Faculty of Xinya College, Tsinghua University": "/logos/faculty-of-xinya-college-tsinghua-university.png",
  "University of Saint Joseph": "/logos/university-of-saint-joseph.png",
  "Kwangwoon University Opticmix": "/logos/kwangwoon-university-opticmix.png",
  "Universiti Sains Malaysia": "/logos/universiti-sains-malaysia.png",
  "Immersive Content Display Center, Deparment of Content Convergence, Kwangwoon University": "/logos/immersive-content-display-center-deparment-of-content-conver.png",
  "UNDP Asia and the Pacific": "/logos/undp-asia-and-the-pacific.png",
  "Hue Institute for Development Studies": "/logos/hue-institute-for-development-studies.png",
  "School of Architecture and Planning University of Auckland": "/logos/school-of-architecture-and-planning-university-of-auckland.png",
  "Binh My Commune, Ho Chi Minh City": "/logos/binh-my-commune-ho-chi-minh-city.png",
  "UN-Habitat": "/logos/un-habitat.png",
  "Korea Institute of Civil Engineering and Building Technology": "/logos/korea-institute-of-civil-engineering-and-building-technology.png",
  "Center for Anticipatory Urban Strategies,Ulsan National Institute of Science and Technology Department of Civil, Urban, Earth, and Environmental Engineering": "/logos/center-for-anticipatory-urban-strategies-ulsan-national-inst.png",
  "Maha Sarakham University": "/logos/maha-sarakham-university.png",
  "Hasselt University": "/logos/hasselt-university.png",
  "UEH": "/logos/ueh.png",
  "University of Trieste": "/logos/university-of-trieste.png",
  "Universiti Teknologi Malaysia (UTM)": "/logos/universiti-teknologi-malaysia-utm.png",
  "Handong Global University": "/logos/handong-global-university.png",
  "College of Design, North Carolina State University": "/logos/college-of-design-north-carolina-state-university.png",
  "OMGEVING": "/logos/omgeving.png",
  "University of Economics Ho Chi Minh City": "/logos/university-of-economics-ho-chi-minh-city.png",
  "National Taiwan Ocean University": "/logos/national-taiwan-ocean-university.png",
  "Department of Computer Engineering, Sejong University": "/logos/department-of-computer-engineering-sejong-university.png",
  "National United University, Taiwan": "/logos/national-united-university-taiwan.png",
  "Korea Institute of Civil Engineering and Building Technology (KICT)": "/logos/korea-institute-of-civil-engineering-and-building-technology.png",
  "ISC Innovation and Technology Incubation Center": "/logos/isc-innovation-and-technology-incubation-center.png",
  "Consulate General of the Republic of Indonesia": "/logos/consulate-general-of-the-republic-of-indonesia.png",
  "Department for Tourism and Transport, University of Applied Sciences, Worms": "/logos/department-for-tourism-and-transport-university-of-applied-s.png",
  "Lee Kuan Yew Centre for Innovative Cities, SUTD": "/logos/lee-kuan-yew-centre-for-innovative-cities-sutd.png",
  "Saythu...linking people and heritage": null,
  "North Carolina State University": "/logos/north-carolina-state-university.png",
  "Leipzig University": "/logos/leipzig-university.png",
  "University of Zurich Leipzig University": "/logos/university-of-zurich-leipzig-university.png",
  "Thammasat University": "/logos/thammasat-university.png"
};

export function logoForOrg(org: string | null | undefined): string | null {
  if (!org) return null;
  return LOGO_MAP[org.replace(/\s+/g, ' ').trim()] ?? null;
}
