// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.
import type { Group, Lab, Participant } from '../types.ts';

export const seedGroups: Group[] = [
  {
    "id": 1,
    "name": "Creative Media Innovation Lab - Entertainment & Heritage Innovation Lab - AI Art & Branding Lab - Digital Media and Sustainable Wellbeing Lab; AI & Sustainability Lab - Immersive Convergence Center",
    "color": "#cc2027",
    "sort_order": 1
  },
  {
    "id": 2,
    "name": "Governance & Policy Planning Lab - New Economy Lab",
    "color": "#e8710a",
    "sort_order": 2
  },
  {
    "id": 3,
    "name": "Living Lab - NetZero Open Lab",
    "color": "#1f9e6e",
    "sort_order": 3
  },
  {
    "id": 4,
    "name": "Public Space Lab - Data Drive & Urban Design Lab - International Center of Urbanism",
    "color": "#2f6fd6",
    "sort_order": 4
  },
  {
    "id": 5,
    "name": "Robotic & AI Lab - Open Lab - 3I Research Center",
    "color": "#7b4bd0",
    "sort_order": 5
  },
  {
    "id": 6,
    "name": "Smart City Research - Move System Lab - Immersive Technology Convergence Center",
    "color": "#128a9c",
    "sort_order": 6
  },
  {
    "id": 7,
    "name": "TIR Lab - BIT Lab - AI & Human Experience Lab",
    "color": "#c0327a",
    "sort_order": 7
  }
];

export const seedLabs: Lab[] = [
  {
    "id": 1,
    "group_id": 1,
    "name": "Creative Media Innovation Lab",
    "sort_order": 1
  },
  {
    "id": 2,
    "group_id": 1,
    "name": "Entertainment & Heritage Innovation Lab",
    "sort_order": 2
  },
  {
    "id": 3,
    "group_id": 1,
    "name": "AI Art & Branding Lab",
    "sort_order": 3
  },
  {
    "id": 4,
    "group_id": 1,
    "name": "Digital Media and Sustainable Wellbeing Lab",
    "sort_order": 4
  },
  {
    "id": 5,
    "group_id": 1,
    "name": "AI & Sustainability Lab",
    "sort_order": 5
  },
  {
    "id": 6,
    "group_id": 1,
    "name": "Immersive Convergence Center",
    "sort_order": 6
  },
  {
    "id": 7,
    "group_id": 2,
    "name": "Governance & Policy Planning Lab",
    "sort_order": 1
  },
  {
    "id": 8,
    "group_id": 2,
    "name": "New Economy Lab",
    "sort_order": 2
  },
  {
    "id": 9,
    "group_id": 3,
    "name": "Living Lab",
    "sort_order": 1
  },
  {
    "id": 10,
    "group_id": 3,
    "name": "NetZero Open Lab",
    "sort_order": 2
  },
  {
    "id": 11,
    "group_id": 4,
    "name": "Public Space Lab",
    "sort_order": 1
  },
  {
    "id": 12,
    "group_id": 4,
    "name": "Data Drive & Urban Design Lab",
    "sort_order": 2
  },
  {
    "id": 13,
    "group_id": 4,
    "name": "International Center of Urbanism",
    "sort_order": 3
  },
  {
    "id": 14,
    "group_id": 5,
    "name": "Robotic & AI Lab",
    "sort_order": 1
  },
  {
    "id": 15,
    "group_id": 5,
    "name": "Open Lab",
    "sort_order": 2
  },
  {
    "id": 16,
    "group_id": 5,
    "name": "3I Research Center",
    "sort_order": 3
  },
  {
    "id": 17,
    "group_id": 6,
    "name": "Smart City Research",
    "sort_order": 1
  },
  {
    "id": 18,
    "group_id": 6,
    "name": "Move System Lab",
    "sort_order": 2
  },
  {
    "id": 19,
    "group_id": 6,
    "name": "Immersive Technology Convergence Center",
    "sort_order": 3
  },
  {
    "id": 20,
    "group_id": 7,
    "name": "TIR Lab",
    "sort_order": 1
  },
  {
    "id": 21,
    "group_id": 7,
    "name": "BIT Lab",
    "sort_order": 2
  },
  {
    "id": 22,
    "group_id": 7,
    "name": "AI & Human Experience Lab",
    "sort_order": 3
  }
];

export const seedParticipants: Participant[] = [
  {
    "id": 1,
    "stt": "6",
    "title": "Prof. Dr.",
    "name": "Haipeng Mi",
    "country": "China",
    "org": "Faculty of Xinya College, Tsinghua University",
    "org_logo_url": null,
    "role": "Director, Media and Interaction Lab (Milab)",
    "email": "mhp@tsinghua.edu.cn",
    "coordinator": "Linh (SMD) - Trang (SMD)",
    "group_id": 1
  },
  {
    "id": 2,
    "stt": "19",
    "title": "Dr.",
    "name": "Filipa Martins",
    "country": "Macao",
    "org": "University of Saint Joseph",
    "org_logo_url": null,
    "role": "Assistant Professor",
    "email": "filipa.martins@usj.edu.mo",
    "coordinator": "Linh (SMD) - Trang (SMD)",
    "group_id": 1
  },
  {
    "id": 3,
    "stt": "26",
    "title": "Dr.",
    "name": "LeeHwan Hwang",
    "country": "Korea",
    "org": "Kwangwoon University Opticmix",
    "org_logo_url": null,
    "role": "Chair of Department of Immersive Convergence Contents CEO",
    "email": "optics.hwang@kw.ac.kr",
    "coordinator": "Linh (SMD) - Trang (SMD)",
    "group_id": 1
  },
  {
    "id": 4,
    "stt": "29",
    "title": "Dr.",
    "name": "Nurul Hanim Romainoor",
    "country": "Malaysia",
    "org": "Universiti Sains Malaysia",
    "org_logo_url": null,
    "role": "",
    "email": "hanim.romainoor@usm.my",
    "coordinator": "Linh (SMD) - Trang (SMD)",
    "group_id": 1
  },
  {
    "id": 5,
    "stt": "37",
    "title": "Prof.",
    "name": "SeungHyun Lee",
    "country": "Korea",
    "org": "Immersive Content Display Center, Deparment of Content Convergence, Kwangwoon University",
    "org_logo_url": null,
    "role": "Director",
    "email": "shlee@kw.ac.kr",
    "coordinator": "Linh (SMD) - Trang (SMD)",
    "group_id": 1
  },
  {
    "id": 6,
    "stt": "13",
    "title": "Mr.",
    "name": "Clinton Moore",
    "country": "",
    "org": "UNDP Asia and the Pacific",
    "org_logo_url": null,
    "role": "Urban Governance Specialist Consultant",
    "email": "clinton.moore@undp.org",
    "coordinator": "Mai (ISCM) - Hoài (ISCM)",
    "group_id": 2
  },
  {
    "id": 7,
    "stt": "14",
    "title": "Dr.",
    "name": "Cung Trong Cuong",
    "country": "Hue, Vietnam",
    "org": "Hue Institute for Development Studies",
    "org_logo_url": null,
    "role": "Director",
    "email": "cuongcung@hueids.vn",
    "coordinator": "Mai (ISCM) - Hoài (ISCM)",
    "group_id": 2
  },
  {
    "id": 8,
    "stt": "27",
    "title": "Prof.",
    "name": "Manfredo Manfredini",
    "country": "NewZealand",
    "org": "School of Architecture and Planning University of Auckland",
    "org_logo_url": null,
    "role": "Associate Professor · Director (Architecture & International Engagement), Deputy Head - Architecture",
    "email": "m.manfredini@auckland.ac.nz",
    "coordinator": "Mai (ISCM) - Hoài (ISCM)",
    "group_id": 2
  },
  {
    "id": 9,
    "stt": "28",
    "title": "Dr.",
    "name": "Nguyen Anh Tuan",
    "country": "Vietnam",
    "org": "Binh My Commune, Ho Chi Minh City",
    "org_logo_url": null,
    "role": "Chairman",
    "email": "tuankts@gmail.com",
    "coordinator": "Mai (ISCM) - Hoài (ISCM)",
    "group_id": 2
  },
  {
    "id": 10,
    "stt": "11",
    "title": "Ms.",
    "name": "Bui Thu Hien",
    "country": "Vietnam",
    "org": "UN-Habitat",
    "org_logo_url": null,
    "role": "Project Coordinator",
    "email": "hienchip762003@gmail.com",
    "coordinator": "Mai (ISCM) - Hoài (ISCM)",
    "group_id": 2
  },
  {
    "id": 11,
    "stt": "22",
    "title": "Mr.",
    "name": "Hoyoon Lee",
    "country": "Korea",
    "org": "Korea Institute of Civil Engineering and Building Technology",
    "org_logo_url": null,
    "role": "Researcher",
    "email": "hylee@kict.re.kr",
    "coordinator": "Hiển (ISCM) - Tú Anh (ISCM)",
    "group_id": 3
  },
  {
    "id": 12,
    "stt": "23",
    "title": "Prof.",
    "name": "Jeongseob Kim",
    "country": "Korea",
    "org": "Center for Anticipatory Urban Strategies,Ulsan National Institute of Science and Technology Department of Civil, Urban, Earth, and Environmental Engineering",
    "org_logo_url": null,
    "role": "Director Professor",
    "email": "jskim14@unist.ac.kr",
    "coordinator": "Hiển (ISCM) - Tú Anh (ISCM)",
    "group_id": 3
  },
  {
    "id": 13,
    "stt": "32",
    "title": "Dr.",
    "name": "Wichitra Singhirunnusorn",
    "country": "Vietnam",
    "org": "Maha Sarakham University",
    "org_logo_url": null,
    "role": "Lecturer",
    "email": "wichitra.s@msu.ac.th",
    "coordinator": "Hiển (ISCM) - Tú Anh (ISCM)",
    "group_id": 3
  },
  {
    "id": 14,
    "stt": "33",
    "title": "Dr.",
    "name": "Sophie Cloes",
    "country": "Belgium",
    "org": "Hasselt University",
    "org_logo_url": null,
    "role": "",
    "email": "sophiecloes@icloud.com",
    "coordinator": "Hiển (ISCM) - Tú Anh (ISCM)",
    "group_id": 3
  },
  {
    "id": 15,
    "stt": "35",
    "title": "Dr.",
    "name": "Hoàng Phi Long",
    "country": "",
    "org": "UEH",
    "org_logo_url": null,
    "role": "",
    "email": "longhp@ueh.edu.vn",
    "coordinator": "Hiển (ISCM) - Tú Anh (ISCM)",
    "group_id": 3
  },
  {
    "id": 16,
    "stt": "5",
    "title": "Assoc. Prof. Dr",
    "name": "Elena Marchigiani",
    "country": "Italy",
    "org": "University of Trieste",
    "org_logo_url": null,
    "role": "Professor, Department of Engineering and Architecture",
    "email": "emarchigiani@units.it",
    "coordinator": "Daniela (ISCM) - Chi (ISCM)",
    "group_id": 4
  },
  {
    "id": 17,
    "stt": "10",
    "title": "Dr.",
    "name": "Adrian Lo",
    "country": "Malaysia",
    "org": "Universiti Teknologi Malaysia (UTM)",
    "org_logo_url": null,
    "role": "Professor",
    "email": "adrianyatwai@utm.my",
    "coordinator": "Daniela (ISCM) - Chi (ISCM)",
    "group_id": 4
  },
  {
    "id": 18,
    "stt": "12",
    "title": "Mr.",
    "name": "Cho Kwanphil",
    "country": "",
    "org": "Handong Global University",
    "org_logo_url": null,
    "role": "Lecturer",
    "email": "kwanphil.cho@handong.edu",
    "coordinator": "Daniela (ISCM) - Chi (ISCM)",
    "group_id": 4
  },
  {
    "id": 19,
    "stt": "15",
    "title": "Prof.",
    "name": "Donghwan Moon",
    "country": "USA",
    "org": "College of Design, North Carolina State University",
    "org_logo_url": null,
    "role": "Assistant Professor",
    "email": "donghwan_moon@ncsu.edu",
    "coordinator": "Daniela (ISCM) - Chi (ISCM)",
    "group_id": 4
  },
  {
    "id": 20,
    "stt": "31",
    "title": "Mr.",
    "name": "Steven Petit",
    "country": "Vietnam",
    "org": "OMGEVING",
    "org_logo_url": null,
    "role": "Creative Director",
    "email": "steven.petit@omgeving.be",
    "coordinator": "Daniela (ISCM) - Chi (ISCM)",
    "group_id": 4
  },
  {
    "id": 21,
    "stt": "1",
    "title": "Prof.",
    "name": "Kelly Shannon",
    "country": "",
    "org": "University of Economics Ho Chi Minh City",
    "org_logo_url": null,
    "role": "Glocal expert, Institute of Smart City and Management",
    "email": "kshannon09@gmail.com",
    "coordinator": "Daniela (ISCM) - Chi (ISCM)",
    "group_id": 4
  },
  {
    "id": 22,
    "stt": "2",
    "title": "Prof.",
    "name": "Bruno De Meulder",
    "country": "",
    "org": "University of Economics Ho Chi Minh City",
    "org_logo_url": null,
    "role": "Glocal expert, Institute of Smart City and Management",
    "email": "brdmeu@gmail.com",
    "coordinator": "Daniela (ISCM) - Chi (ISCM)",
    "group_id": 4
  },
  {
    "id": 23,
    "stt": "3",
    "title": "Prof. Dr.",
    "name": "Bor-Jiunn Wen",
    "country": "Taiwan",
    "org": "National Taiwan Ocean University",
    "org_logo_url": null,
    "role": "Professor and Chair, Department of Mechanical and Mechatronic Engineering",
    "email": "jiunner@mail.ntou.edu.tw",
    "coordinator": "Bá Sơn (3I) - Đức Cường (3I) - Hoàng Kha (3I)",
    "group_id": 5
  },
  {
    "id": 24,
    "stt": "7",
    "title": "Prof. Dr.",
    "name": "Kim Yong-Guk",
    "country": "Korea",
    "org": "Department of Computer Engineering, Sejong University",
    "org_logo_url": null,
    "role": "Professor, Department of Computer Engineering",
    "email": "ykim@sejong.ac.kr",
    "coordinator": "Bá Sơn (3I) - Đức Cường (3I) - Hoàng Kha (3I)",
    "group_id": 5
  },
  {
    "id": 25,
    "stt": "18",
    "title": "Prof",
    "name": "Fan-Bean Wu",
    "country": "Taiwan",
    "org": "National United University, Taiwan",
    "org_logo_url": null,
    "role": "Professor",
    "email": "fbwu@nuu.edu.tw",
    "coordinator": "Bá Sơn (3I) - Đức Cường (3I) - Hoàng Kha (3I)",
    "group_id": 5
  },
  {
    "id": 26,
    "stt": "24",
    "title": "Dr.",
    "name": "Junggon Sung",
    "country": "Korea",
    "org": "Korea Institute of Civil Engineering and Building Technology (KICT)",
    "org_logo_url": null,
    "role": "Senior Research Fellow",
    "email": "jgsung@kict.re.kr",
    "coordinator": "Bá Sơn (3I) - Đức Cường (3I) - Hoàng Kha (3I)",
    "group_id": 5
  },
  {
    "id": 27,
    "stt": "36",
    "title": "Mr.",
    "name": "Lâm Nguyễn Hải Long",
    "country": "",
    "org": "ISC Innovation and Technology Incubation Center",
    "org_logo_url": null,
    "role": "Director",
    "email": "long@vietnamisc.com",
    "coordinator": "Bá Sơn (3I) - Đức Cường (3I) - Hoàng Kha (3I)",
    "group_id": 5
  },
  {
    "id": 28,
    "stt": "4",
    "title": "Ms.",
    "name": "Carolina Tinangon",
    "country": "Indonesia",
    "org": "Consulate General of the Republic of Indonesia",
    "org_logo_url": null,
    "role": "Consul General",
    "email": "c.tinangon@kemlu.go.id",
    "coordinator": "An (ISCM) - Tâm (ISCM)",
    "group_id": 6
  },
  {
    "id": 29,
    "stt": "16",
    "title": "Prof.",
    "name": "Ducksu Seo",
    "country": "Korea",
    "org": "Handong Global University",
    "org_logo_url": null,
    "role": "Associate Professor",
    "email": "handonge@handong.edu",
    "coordinator": "An (ISCM) - Tâm (ISCM)",
    "group_id": 6
  },
  {
    "id": 30,
    "stt": "20",
    "title": "Prof.",
    "name": "Frank Fichert",
    "country": "Germany",
    "org": "Department for Tourism and Transport, University of Applied Sciences, Worms",
    "org_logo_url": null,
    "role": "Vice Dean",
    "email": "frank.fichert@hs-worms.de",
    "coordinator": "An (ISCM) - Tâm (ISCM)",
    "group_id": 6
  },
  {
    "id": 31,
    "stt": "21",
    "title": "Dr.",
    "name": "Harvey Neo",
    "country": "Singapore",
    "org": "Lee Kuan Yew Centre for Innovative Cities, SUTD",
    "org_logo_url": null,
    "role": "Professorial Fellow",
    "email": "harvey_neo@sutd.edu.sg",
    "coordinator": "An (ISCM) - Tâm (ISCM)",
    "group_id": 6
  },
  {
    "id": 32,
    "stt": "25",
    "title": "Dr.",
    "name": "Krupa Rajangam",
    "country": "India",
    "org": "Saythu...linking people and heritage",
    "org_logo_url": null,
    "role": "Founder director",
    "email": "rajangamk@gmail.com",
    "coordinator": "An (ISCM) - Tâm (ISCM)",
    "group_id": 6
  },
  {
    "id": 33,
    "stt": "8",
    "title": "Dr.",
    "name": "Soolyeon Cho",
    "country": "USA",
    "org": "North Carolina State University",
    "org_logo_url": null,
    "role": "Director, Building Energy Technology Lab",
    "email": "scho3@ncsu.edu",
    "coordinator": "Quyên (SMD) - Thanh (UII) - Huy (BIT)",
    "group_id": 7
  },
  {
    "id": 34,
    "stt": "9",
    "title": "Prof. Dr.",
    "name": "Utz Dornberger",
    "country": "Germany",
    "org": "Leipzig University",
    "org_logo_url": null,
    "role": "Director, SEPT Competence Center",
    "email": "dornberg@uni-leipzig.de",
    "coordinator": "Quyên (SMD) - Thanh (UII) - Huy (BIT)",
    "group_id": 7
  },
  {
    "id": 35,
    "stt": "17",
    "title": "Prof.",
    "name": "Erik Wende",
    "country": "Germany",
    "org": "University of Zurich Leipzig University",
    "org_logo_url": null,
    "role": "Professor",
    "email": "erikwende@mac.com",
    "coordinator": "Quyên (SMD) - Thanh (UII) - Huy (BIT)",
    "group_id": 7
  },
  {
    "id": 36,
    "stt": "30",
    "title": "Prof.",
    "name": "Pawinee Imtrakul",
    "country": "Thailand",
    "org": "Thammasat University",
    "org_logo_url": null,
    "role": "Director of the Center of Excellence in Urban Mobility Research and Innovation Professor, Department of Urban Environmental Planning and Development, Faculty of Architecture and Planning",
    "email": "iamtrakul@gmail.com",
    "coordinator": "Quyên (SMD) - Thanh (UII) - Huy (BIT)",
    "group_id": 7
  },
  {
    "id": 37,
    "stt": "34",
    "title": "Dr.",
    "name": "Christopher Han",
    "country": "Korea",
    "org": "UEH",
    "org_logo_url": null,
    "role": "",
    "email": "christopher.han@ueh.edu.vn",
    "coordinator": "Quyên (SMD) - Thanh (UII) - Huy (BIT)",
    "group_id": 7
  }
];
